[gd_resource type="Theme" load_steps=5 format=2]

[sub_resource type="StyleBoxFlat" id=1]
bg_color = Color( 0.752941, 0.752941, 0.752941, 1 )
border_width_left = 2
border_width_top = 2
border_width_right = 2
border_width_bottom = 2
border_color = Color( 0.25098, 0.25098, 0.25098, 1 )
content_margin_left = 6.0
content_margin_top = 4.0
content_margin_right = 6.0
content_margin_bottom = 4.0

[sub_resource type="StyleBoxFlat" id=2]
bg_color = Color( 0.752941, 0.752941, 0.752941, 1 )
border_width_left = 2
border_width_top = 2
border_width_right = 2
border_width_bottom = 2
border_color = Color( 0.25098, 0.25098, 0.25098, 1 )
content_margin_left = 7.0
content_margin_top = 5.0
content_margin_right = 5.0
content_margin_bottom = 3.0

[sub_resource type="StyleBoxFlat" id=3]
bg_color = Color( 0, 0, 0.501961, 1 )
border_width_left = 2
border_width_top = 2
border_width_right = 2
border_width_bottom = 2
border_color = Color( 0.25098, 0.25098, 0.25098, 1 )

[sub_resource type="StyleBoxEmpty" id=4]

[resource]
default_color = Color( 0, 0, 0, 1 )
Button/colors/font_color = Color( 0, 0, 0, 1 )
Button/colors/font_color_hover = Color( 0, 0, 0, 1 )
Button/colors/font_color_pressed = Color( 0, 0, 0, 1 )
Button/styles/focus = SubResource( 4 )
Button/styles/hover = SubResource( 1 )
Button/styles/normal = SubResource( 1 )
Button/styles/pressed = SubResource( 2 )
Label/colors/font_color = Color( 0, 0, 0, 1 )
LineEdit/colors/font_color = Color( 0, 0, 0, 1 )
LineEdit/colors/font_color_selected = Color( 1, 1, 1, 1 )
LineEdit/colors/selection_color = Color( 0, 0, 0.501961, 1 )
LineEdit/styles/focus = SubResource( 1 )
LineEdit/styles/normal = SubResource( 1 )
Panel/styles/panel = SubResource( 1 )
PanelContainer/styles/panel = SubResource( 1 )
ProgressBar/styles/bg = SubResource( 2 )
ProgressBar/styles/fg = SubResource( 3 )
TextEdit/styles/focus = SubResource( 1 )
TextEdit/styles/normal = SubResource( 1 )
Tree/styles/bg = SubResource( 1 )
Tree/styles/bg_focus = SubResource( 1 )
