extends Resource
class_name DomeIntroPipeVisualBake

# Generated by tools/bake_pipe_network.gd from DomeIntro_PipeNetworkSource.
export(bool) var orient_leaks_inward: bool = true
export(bool) var orient_valves_inward: bool = true
